### PR TITLE
Add "cart" to User

### LINKED ISSUE #79: Add Shopping Cart to User
- [x] Create An Array of "Items" that will act as a shopping cart for a user
- [x] Create an Update Mutation that will take in an item as a parameter and add push it to the array of Items
- [x] Test Code
- [ ] Write about Code

### PR DESCRIPTION
**Pull request by Yarmoski**
Resolves #79

### CODE REVIEW

**Comment by Yarmoski** [comment]
# Changes

- User "cart"
  - typedefs.ts
    - UserArguments
      - cart: [ID!]
    - updateCartArguments
      - userId: ID!
      - itemId: ID!
  - User.ts
    - add "cart" (array of item ids)
  - UserResolver.ts
    - updateCart mutation
  - ItemResolver.ts, ProductResolver.ts
    - update delete mutations to remove from cart if needed

**Review by alfredzhuang — APPROVED** [review]

**Review by andreidimaano — CHANGES_REQUESTED** [review]
The Update Cart function works

- [ ] Add Cart to Users Query return
- [ ] Create a Get Cart Query

**Comment by Yarmoski** [comment]
# Changes
- add cart to users query in UserResolvers.ts
- add getCurrCart in UserResolvers.ts
  - not sure how to test this; I followed the "me" query's structure

**Review by andreidimaano — CHANGES_REQUESTED** [review]
missing cart: [Item!]! 
- [x] add cart to users typedef
image

- [x] parse the cart items
image


Everything else is good! 

image

image

**Review by andreidimaano — APPROVED** [review]
GUD CODE

**Pull request merged**
